server:
  port: 8123

springdoc:
  swagger-ui:
    operationsSorter: method
    groups-order: DESC
    disable-swagger-default-url: 'true'
    path: /swagger-ui.html
    display-request-duration: 'true'
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  show-actuator: 'true'
  default-consumes-media-type: application/json
  paths-to-match: /api/**
